# Generated by Django 3.0.6 on 2020-05-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snip', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
